# Generated by Django 4.2.16 on 2024-12-03 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_number", models.CharField(max_length=4, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("seniority", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filedAgainst", models.CharField(max_length=30)),
                ("ticketType", models.CharField(max_length=30)),
                (
                    "severity_level",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("daysOpen", models.IntegerField(blank=True, default=0, null=True)),
                ("priority", models.FloatField(blank=True, default=1, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.employee"
                    ),
                ),
            ],
        ),
    ]
